# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    rate_limiter:
        # see https://symfony.com/doc/current/reference/configuration/framework.html#rate-limiter
        # ici on a 2 politiques de rate limit
        # 1 pour les api anonymes
        # 1 pour les api authentifiées
        # on peut aussi avoir une politique par route, ...
        # https://symfony.com/doc/current/rate_limiter.html#rate-limiter-configuration
        anonymous_api:
            # use 'fixed_window' if you prefer that policy
            policy: 'sliding_window'
            limit: 2
            interval: '1 minutes'
        authenticated_api:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
